### ISSUE TITLE
unfortunately  there's an error nexus 5 running DU 5.0.2

### ISSUE THREAD

**Issue by xs37** [DirtyUnicorns/All-Projects#1]
There's an error and I have tryed so hard to fix it cause I thought it was my fault but I can't seem to find out whether it was my doing or just a bad spot in the ROM but I keep getting "unfortunately android.processes. media" has crashed please give me some guidance and oh just saying love the ROM keep up the great work guys and or girls love the ROM feels like I found my new favorite thank you for your time have a good one and please keep them comming

**Comment by nychitman1** [comment]
Report issues on jira, not Github.
